### ISSUE TITLE
balancing issue

### ISSUE THREAD

**Issue by wait-a-second** [tobspr/shapez.io#1001]
balancers don't work with different types of items
 and they are inconsistent, this balancer in the video is an 8 to 8 balancer and it has two 4 to 4 balancers in it
[ballancer.zip](https://github.com/tobspr/shapez.io/files/5591196/ballancer.zip)

**Comment by EmeraldBlock** [comment]
while i can't watch the video right now, here might be reasons why for inconsistency:
1. items are discrete objects, not continuous flows. This means that, if a stream of alternating items enter a balancer, they may be split back into pure streams.
2. balancers are interesting in that they force two full input belts to "mix" (instead of swap or stay the same) if they enter at about the same time. However, if the two belts are slightly off from each other, they may end up not mixing.

**Comment by tobspr** [comment]
What @EmeraldBlock said
