### ISSUE TITLE
Short Code "Shortcuts"

### ISSUE THREAD

**Issue by Nocturn78** [tobspr/shapez.io#1006]
When asked for a shortcode it would be useful to define a whole layer by describing a single shape.

So when you want to define a whole rectange of the color blue, you'd normally write:
**RbRbRbRb**

A shortcut to get the same result by writing just:
**Rb**
would make a really nice quality-of-life feature.

Also with multiple layers:
**Cw:Wy** should be parsed into **CwCwCwCw:WyWyWyWy**

(Nocturn#6170 on discord if someone wants to discuss this there)

**Comment by edorfaus** [comment]
This could be a nice shortcut for places that only expect a shape code, but it can cause problems in other places (like map markers) that accept general text in addition to shape codes, since some of the two-letter combinations are existing words or abbreviations (in English at least). Trying to write a word and getting a shape instead could be annoying. Only accepting them in code-only inputs is probably not a good solution either, since inconsistency in which codes are accepted depending on where you write them could be confusing.

Maybe some syntax could be devised to avoid this problem? E.g. some symbol character to mark "the next/previous part is a short-form shape code"? (An example could be "Wu*" or "Cr*:Wy*", though I'm not sure if that's the best way to do it. Or maybe start with a colon, e.g. ":Wu", since colons are already used in shape codes?)

This should probably be considered together with #959 (for color-only symbols), since such syntax has also been suggested there, maybe this could use the same character(s) - or if not, it needs coordination to avoid using the same one. (If one turns out to be necessary that is.)

**Comment by Nocturn78** [comment]
Map markers, as they are now, don't allow short code with additional text. Eg "RbRbRbRb go brrrr" creates a Marker with exactly this text and no symbol. I didn't check out the code now but i assume symbols will be used if the whole string can be parsed into one. If it can't, it shows the text. So special characters would not be necessary

**Comment by EmeraldBlock** [comment]
I believe that they mean that someone could have a marker containing just an abbreviation (like "Sc" or something), and they do not want it to be parsed as a shape code.

**Comment by edorfaus** [comment]
What EmeraldBlock said, and also keeping in mind potential improvements to the markers that would allow them to contain both codes and text at the same time (e.g. as per PR #940, which tobspr seemed to like and marked as "planned", which suggests a merge isn't unlikely).

**Comment by Nocturn78** [comment]
oh well i didn't know about that marker improvements. if that's a gonna be a thing one simply had to decide wheiter "short short codes" will be parsed and converted into shapes or interpreted as "words". I mean, would someone want his markers labeled as "Rb" or "Wc"? No idea why someone whould want that

**Comment by EmeraldBlock** [comment]
Obviously, not all short short codes make sensible abbreviations, but some of them may.

I think a good solution would be to just use a prefix character at the beginning of a shape key, which should also work with the marker improvements PR

**Comment by edorfaus** [comment]
A quick search through the English word list on my system (I think it's used for spell checkers? Not sure) for the two-letter codes gave me four known words/abbreviations: Cr Cu Sb Wu

A dictionary lookup (on dict.org) showed me that the first three all have several meanings, including all of them being metals and Sb being short for symbol - while the last is a language (a dialect of Chinese).

Whether it makes sense to use any of these in/as map markers is probably rather subjective, and depends on what associations someone has with them. (Also, I haven't checked other languages, which may have different words that are spelled like these or other codes. The shorter the codes are, the more likely such collisions are to happen in _some_ language.)

I agree that using a prefix character sounds like a good solution. (Especially if done carefully - I've seen plenty of problems with careless conversion of smileys, hopefully we can avoid getting equivalent problems here, while still enabling short-short codes like this.)

**Comment by Nocturn78** [comment]
hehe thank you edorfaus for the research. I totally agree, the most secure way to avoid any issues is a prefix. i think just a colon (**:**) as you mentioned before would be a really nice one

**Comment by tobspr** [comment]
I'd be happy to accept a PR which allows to do `Cr*` since that is very uncommon. It should only allow this in the markers section though, in order to not screw up peformance. Closing for now though, since I for myself don't plan to implement this
