### ISSUE TITLE
Add the ability to change where the keybind for hub (space as default) take you?

### ISSUE THREAD

**Issue by boiimakillu** [tobspr/shapez.io#1007]
I tried making a pull request for this, but gave up after I realized the most I know about coding is mid-level BASH and that Python is mean. The idea is that you could have a one-at-a-time checkbox up in the waypoints menu, and whichever one was selected would become the default "home", meaning that whenever you hit the bind that would normally take the player to the hub, it would instead take you to that marked waypoint. Another quick thing, maybe consider adding a confirmation for deleting waypoints? I have deleted a few on accident, and even though it isn't too much of an issue, it is kind of annoying having to figure out which one you deleted or where it was.

**Comment by edorfaus** [comment]
Regarding deleting waypoints, I think adding an undo function would be much better than adding a confirmation, since it has been shown that confirmations just train people to click past without thinking. It's already two clicks to delete (open edit box, then delete button) - I don't think adding a third click would help much, it would just make it more annoying when you do want to delete. Undo, on the other hand, is not in the way normally, and (even if it's just single-level) is still available even if it takes a few moments to realize you didn't want to do that. (Bonus points if it tells you what it will undo before you click it (e.g. hover text), or has redo in case you undid the wrong thing.)

Regarding the main feature request, I would like it even more if I could either select several waypoints that the keybind would switch between, or add new keybinds to specific waypoints, so it would be easier to move back and forth between two (or more) places. (I sometimes do that, either to copy or to compare, or to check how I did something while building something new - but using the mouse to click the correct waypoint quickly, while looking at something else, isn't easy.)

**Comment by tobspr** [comment]
Hm, I have some ideas, but nothing planned exactly, feel free to make a PR, I'll close this in the meantime
