### ISSUE TITLE
Feature Request (Smart filter)

### ISSUE THREAD

**Issue by Kfftw-Stardust** [tobspr/shapez.io#1045]
It detects what is moving through it so it can easier trash shapes that you don't want. 
For example trash shapes that comes out of the freeplay machine

**Comment by EmeraldBlock** [comment]
Do you mean the already-existing filter? (which filters items by if they are/aren't a specific item)

Otherwise, your idea doesn't make much sense - knowing where a shape came from would require shapes to me "marked" in some way, which is pretty weird. (though if done right, it could have some cool applications, but I feel it really isn't a fit for the game as it is right now)

**Comment by Kfftw-Stardust** [comment]
I was dumb and didn't reallize it worked that way so this was dumb of me
