### ISSUE TITLE
Is this code the full thin or just a demo?

### ISSUE THREAD

**Issue by Derpez** [tobspr/shapez.io#1296]

**Comment by albiini** [comment]
Full game

**Comment by EmeraldBlock** [comment]
it's basically any version of the game, just depends how you build it

**Comment by Derpez** [comment]
so can it be like the steam version or like... I just want to know if it has all of the features the steam one has or if its like a demo because its getting updated regularly so I would assume its the full thing.

**Comment by EmeraldBlock** [comment]
it gets updated regularly since those are new changes to be added in the next release. It can be the standalone, but won't be a steam game since you'd have to buy it off Steam for that. (Note this also means you can't access the Puzzles DLC servers without buying the DLC on Steam.)

(also please close this issue; this is more a question than a bug/feature request etc, feel free to ask questions in the discord server)

**Comment by Derpez** [comment]
Okay i will close it but i am trying to build it but im getting some errors

**Comment by Dax911** [comment]
> it's basically any version of the game, just depends how you build it

```bash
yarn gulp --tasks-simple
```
is great for seeing all these options but they aren't super clear.  Is there a resource available or a place where simple descriptors are available for reference rather than hunting thru the gulp file?
