### ISSUE TITLE
Subtle Bug On Pasting Complex Blueprint

### ISSUE THREAD

**Issue by evanrinehart** [tobspr/shapez.io#214]
This game is so great! Hopefully you can figure out what's causing this paste error...

![shapez-bug-1](https://user-images.githubusercontent.com/1022635/84939281-b7523f80-b0a3-11ea-8917-4f482060ec3e.png)
![shapez-bug-2](https://user-images.githubusercontent.com/1022635/84939284-b9b49980-b0a3-11ea-9cc4-5eb316964a10.png)
![shapez-bug-3](https://user-images.githubusercontent.com/1022635/84939287-bb7e5d00-b0a3-11ea-8a3f-6170287957d4.png)
![shapez-bug-4](https://user-images.githubusercontent.com/1022635/84939290-bd482080-b0a3-11ea-82e0-4f5f2dd39976.png)

**Comment by tobspr** [comment]
Its a known bug, hopefully will get to it with the next release! Closing it since its already on my todo list

**Comment by evanrinehart** [comment]
Ah shucks. It still seems to be happening in latest update (1.1.17). And people are still posting this issue it seems. Maybe make a master issue, consolidate all the screenshots and leave it open.

**Comment by tobspr** [comment]
Good idea

**Comment by Telos06** [comment]
My quick attempt to debug this suggests that the bug stems from the logic in [updateSurroundingBeltPlacement](https://github.com/tobspr/shapez.io/blame/master/src/js/game/systems/belt.js#L116).  (side note: the process to get set up on gitpod was pretty seemless, so kudos for that!)

A very simple fix might be to remove updateSurroundingBeltPlacement. Arguably this bug is worse than missing this feature.  Without the feature, some belts have to manually re-oriented, but it's not very surprising when they don't orient themselves automagically.

Before pursuing a more complex fix, I'd personally be keen to understand what obstacles there are for unit testing a fix? Or more generally, testing that a copy of a blueprint always yields an identical blueprint?

**Comment by tobspr** [comment]
Already tracking here: https://trello.com/c/rHYkhx4Z/294-pasting-blueprints-sometimes-breaks-buildings-pastes-incorrectly
And also its not as simple as what you suggested @Telos06
