### ISSUE TITLE
Crashes immediately on startup

### ISSUE THREAD

**Issue by freijon** [tobspr/shapez.io#348]
I just bought the game on Steam but I can't even start it:
First I had to `chown root:root chrome-sandbox` and `chmod 4755 chrome-sandbox`. Once I figured that out I'm now stuck with the following error:

`(shapezio:4541): Gtk-WARNING **: 13:50:38:992: cannot open display:  :0`

Any help how I could get the game working?

EDIT:
Im using:
- Gentoo 64-bit
- sway (Wayland)

**Comment by tobspr** [comment]
https://trello.com/c/C7wsfgQi/253-add-no-sandbox-to-fix-game-not-starting-on-linux

**Comment by freijon** [comment]
It's not a sandboxing issue as described in your link.
I got it to work with the following env variable: `GDK_BACKEND=x11`

**Comment by xnuk** [comment]
I have same problem on Wayland environment. And I found this game is packed with Electron 10:

https://github.com/tobspr/shapez.io/blob/0751eec7d579dab449ef93f72a1e11dac120a324/electron/package.json#L12-L14

[Since Electron 12+ supports Wayland](https://github.com/electron/electron/pull/26022), bumping up to latest Electron version could solve the problem. @tobspr

**Comment by xnuk** [comment]
[`1f22327` (#1154)](https://github.com/tobspr/shapez.io/pull/1154/commits/1f22327679d680b43bdd4ef56dd393acdbda6270) touches only patch version of Electron. um okay but why :eyes:
