### ISSUE TITLE
Waypoints allows for duplicate names

### ISSUE THREAD

**Issue by bbugh** [tobspr/shapez.io#36]
I accidentally named something "blue side" twice, which is possible in the game. Seems like it could do a uniqueness check. Something like this, though the lack of validation feedback on the forms could be improved to display what the actual validation failure is.

```diff
diff --git a/src/js/game/hud/parts/waypoints.js b/src/js/game/hud/parts/waypoints.js
index 746145b..ffcc8bf 100644
--- a/src/js/game/hud/parts/waypoints.js
+++ b/src/js/game/hud/parts/waypoints.js
@@ -140,7 +140,7 @@ export class HUDWaypoints extends BaseHUDPart {
             id: "markerName",
             label: null,
             placeholder: "",
-            validator: val => val.length > 0 && val.length < 15,
+            validator: val => val.length > 0 && val.length < 15 && this.waypoints.every((wp) => wp.label !== val),
         });
 
         const dialog = new DialogWithForm({
```

**Comment by tobspr** [comment]
I actually didn't implement that because I didn't want to limit the player. *If* I were to implement this, then there would also have to be an error message added showing that this name is already taken (As you mentioned). If both of this is in a PR I'd be happy to accept it, however adding it would require to extend the Forms dialog
