### ISSUE TITLE
Balancer behavior is incosistent

### ISSUE THREAD

**Issue by Toastgeraet** [tobspr/shapez.io#809]
One image speaks a thousand words...

![grafik](https://user-images.githubusercontent.com/7590096/95616590-50013680-0a6a-11eb-9201-9dc0982e452f.png)

**Comment by EmeraldBlock** [comment]
My understanding of the balancer:

Normally, the balancer will send its first input to the left, its second input to the right, and so on, alternating inputs. BUT, if two items enter at the same time, or almost the same time, the balancer will only update which side it will output to once.

So if two items enter simultaneously, then a third enters afterwards, the third is outputted to the *right* instead of the left. It is with this "quirk" that balancers are able to balance two full lanes by type, except... when that happens.

**Comment by Toastgeraet** [comment]
Yes i agree with you, but in a game like this, i think balancers should have a clearly defined behaviour. I consider this a bug.

**Comment by pepkin88** [comment]
For me, it has a clearly defined behavior – it balances the throughput. However, it does not guarantee balancing the types.

**Comment by Toastgeraet** [comment]
@pepkin88 I understand your point. But unfortunately the throughput can be inaccurate (see tick rate), why the above shown cases can change at any point.

So using both input and both outputs at the same type, while having different objects is never a reliable solution.

To me this feels like a bug. Apparently it does not to other people.

I guess this can be closed then.

**Comment by pepkin88** [comment]
@Toastgeraet You could guarantee mixing the inputs like this:

![image](https://user-images.githubusercontent.com/1028647/96482683-2c917500-123c-11eb-8deb-43acd9b36d25.png)

**Comment by tobspr** [comment]
I don't think the balancers job should be to distribute the items in a specific manner, it should just try to distribute it evenly. Everything else should be done by a filter anyways
