### ISSUE TITLE
Low framerate in standalone version while browser version runs fine

### ISSUE THREAD

**Issue by jacekowski** [tobspr/shapez.io#924]
Hi

For some unknown reason desktop version framerate is extremely low on my PC (works fine on a slower laptop).
I've imported my save into browser version and i'm getting acceptable ~50, while desktop version running at the same time with same save and same part of the factory displayed only get 7-8 (both set to same tickrate of 60Hz).
See attached screenshot.

![shapezio](https://user-images.githubusercontent.com/9898247/96907094-af137200-1492-11eb-81c6-8ecef650657a.png)

**Comment by jfxg** [comment]
I've been dealing with fairly slow performance and constant low FPS between 5-10 in my standalone Steam version as well, I just assumed I had a ton of stuff... but after seeing this I imported the save back into the browser to check and immediately saw a much smoother 20-30 fps. So, I guess I'm seeing the same thing too!

**Comment by derekShaheen** [comment]
This is also happening to me. Runs okay in the desktop version, but considerably better in the browser. Both at 60 tick rate.

**Comment by derekShaheen** [comment]
I believe I have found the cause of this issue. This is related to the high quality textures found in the Steam version. Switch to low textures and the performance will match the browser.

**Comment by jfxg** [comment]
I have all of the performance options turned off already, framerate is still terrible compared to browser. I doubt it’s actually the textures causing the poor performance, but disabling them would no doubt improve performance regardless.

**Comment by jacekowski** [comment]
It looks like lack of GPU acceleration - on both machines chrome is using gpu acceleration and FPS is acceptable, Standalone version is only using GPU acceleration on one machine but not the other (and that one has low FPS).

**Comment by derekShaheen** [comment]
Unfortunately this issue is causing my belts to be limited to 15/s when at 60hz. When increasing to 240hz, they now work at the proper rate, but the FPS is unplayable. When running in the browser, again it works great, but I'm still limited to 60hz, which is limiting my belt output. Possible request: please allow us to associate our Steam account with the website to unlock the full version of the game if we purchased it on Steam. This would at least allow us to effectively bypass the issue until it is solved.

**Comment by tobspr** [comment]
Try running the game directly and not via steam, that's really all I can suggest :/ Also maybe your OS is doing weird stuff with the application

**Comment by H6LS1S** [comment]
The same, in the browser the number of FPS is ~ 80-90, and in steam ~ 10-12. I tried different settings for Proton and for the game itself, I got a maximum of 4 additional frames. I will try one of these days to build the game from source and see if there is a difference. But it would be nice if there was a possibility of authorization in the web version of the game via Steam, since buying the game and playing the demo version in the browser is a doubtful pleasure. 

[Steam API](https://partner.steamgames.com/doc/features/auth#6) works with OpenID, so integrating it shouldn't be a big problem. You can try a bundle from steam-passport and firebase auth with a custom authorization provider


CPU: i5 6440HQ
GPU: HD Graphics 530

Kernel: 5.13.15-194
OS: Solus OS 4.3

Proton: 6.3-6
Google Chrome: 93.0.4577.63

**Comment by H6LS1S** [comment]
https://github.com/electron/electron/issues/13368
