### ISSUE TITLE
[Feature Request] "Clear belts" button / Delete storage button / MAM mode?

### ISSUE THREAD

**Issue by darkwater4213** [tobspr/shapez.io#974]
These are all similar in concept, so I'm presenting them in the same thing.

1. A "clear belts" button has probably been mentioned before -- I saw the idea on the subreddit more than once -- but this version only clears belts. Selecting an area and then pressing it would only clear belts in that area. Shift-Clicking or right-clicking it would clear all shapes except those in Storage.

2. Delete Storage would remove all shapes from all storage buildings. Again, if an area were selected when the button is pressed, it would only apply to that area. 

Both ideas 2 and 3 should probably have a popup confirmation dialog.

3. MAM mode would only become available once you are in freeplay. It would be in the advanced settings tab. What it would do is clear all belts and "marked" storage when the set level is cleared. (You would "mark" a storage building by clicking on it with an empty cursor in freeplay. Clicking on a marked storage building would revert it to normal. By default, MAM mode would automatically turn off after every level, but this could be toggleable in settings.

Maybe these ideas would only be available in the standalone?

**Comment by EmeraldBlock** [comment]
1 and 2 both sound pretty neat, though for 2, I feel that it should operate by a storage-by-storage basis (hover over a storage and press a key or something), but with hold and drag support in case there's a lot to clear. Also, maybe an option to clear hub shapes?

3 feels too much of a leap in automation compared to what's currently in the game, and it's a little oddly specific. It might be better to implement a new system that lets you automatically clear all shapes from a storage (maybe a new wire input pin?)

**Comment by darkwater4213** [comment]
Hmm. That does sound a bit more reasonable. However, The point of 3 is that it _is_ a specific function, for use when you have a Make-Anything Machine (hence the name). Most of these have a "dump gate" at the hub; the idea is that it clears all the shapes from the storage buildings in the "dump gate" so it doesn't mess up the system with the new shapes incoming.

**Comment by edorfaus** [comment]
I took the problem of clearing the dump gate storage as part of the challenge, and solved it by making a shape counter that triggers the dumping when I have just enough of the target shape instead of waiting until the storage is full. That way, the dump gate storage typically empties out in just a few seconds after the level changes, which is long before the MAM has generated enough of the next shape to be a problem, and it also takes less time to "fill up" before dumping since it doesn't need as many of the shape.

I'll admit that this savefile is only at level 115 though, and that its MAM takes a bit of time to really get going with new shapes (I'm still working on optimizing it) - it currently seems to need about 92 seconds per level. (From one level-up to the next, including the build-up and dump time.) So this might be harder to do on later levels, or if your MAM switches shapes faster.

**Comment by tobspr** [comment]
Except for 1) this sounds way too specific. I'll think about 1, for the meantime you can just cut and re-paste the area

**Comment by darkwater4213** [comment]
> Except for 1) this sounds way too specific. I'll think about 1, for the meantime you can just cut and re-paste the area

Yeah, that's what I've been doing for a while now. If I had the time (I don't, really) I could probably make a PR for this; it doesn't seem too hard.
