### ISSUE TITLE
[Feature Request] The cursor keys should move the map like WASD

### ISSUE THREAD

**Issue by Mocha2007** [tobspr/shapez.io#980]
I find myself occasionally trying to move around with the cursor keys but then realize only WASD works... it would be nice to be able to use both!

**Comment by EmeraldBlock** [comment]
Tack on double keybindings to that, maybe

**Comment by darkwater4213** [comment]
So... Add a feature for multiple keys doing the same thing? I like that idea (if I'm interpreting it correctly).

Maybe also sync settings and keybindings across savegames? Just a thought.

**Comment by EmeraldBlock** [comment]
Thought settings are the same across an entire game already - did you mean between games?

Also yeah, that's what I meant

**Comment by darkwater4213** [comment]
What I meant was that if you download a savegame, and import it onto a different copy of the game, you would still have to set the settings however you wanted. What I was trying to suggest is that settings are savegame-specific, not game-specific. In other words, the savegame itself would have a little string tagged onto it that dictates what the settings for that savegame are. I hope that was clearer... o.O

**Comment by EmeraldBlock** [comment]
That would be an interesting idea, though I feel most settings make more sense applied to the entire game (light/dark mode, keybindings, etc.) I can see how settings like performance options make more sense applied to each save individually - maybe there could be two separate categories? Not too sure

**Comment by darkwater4213** [comment]
Yeah, I was thinking about that. Maybe a "setting" that syncs all other settings that are currently applied to that savegame? And when you load a savegame with settings applied, it overrides current settings o=for that savegame only...? Sory if this is kind of ambiguous. I'll try to better articulate it later.

**Comment by edorfaus** [comment]
I agree with EmeraldBlock that for most settings it wouldn't make much sense to keep them in the savegame files, as it could cause a lot of problems with the settings being different between different savegames, or having someone else's controls etc. suddenly apply to you when you just wanted to take a look at their savegame.

I think that, especially for the purpose of moving your own preferred settings between installations of the game, it would make more sense to have a separate function for exporting and importing those settings, to/from a separate file (not a savegame).

That would also allow for other purposes more easily, like making a backup of your settings before you try changing them around, and would avoid the problem of having to change your settings several times if you have several savegames you switch between before you realize you want a setting set a different way.

There _are_ some settings (like tick frequency) that it probably makes more sense to keep with the savegame, since they can affect how that savegame works (especially for machines that use wires-based timing). But then you get into intricacies like potentially having multiple values for the same setting (a default value (for new games), a per-game value, maybe even a global override to stop savegames from setting it too high (maybe min/max instead of override?)...), and making it clear in the UI which of those you change where, and so on. And that's after deciding which settings belong to which category.

**Comment by darkwater4213** [comment]
> it would make more sense to have a separate function for exporting and importing those settings, to/from a separate file (not a savegame).

Yeah, this is probably a better idea. Maybe as a standard `.json` file?

**Comment by tobspr** [comment]
I don't see any benefit here.. also, double keybindings is maybe nice to have but I mean you can either use WASD or the arrow keys depending on what you bind to it, so I'll close it for now
