### ISSUE TITLE
Selected tool resets at each "level X has been completed"

### ISSUE THREAD

**Issue by scikadaei** [tobspr/shapez.io#998]
For example, while placing belts, I might be in the middle of using the belt planner to place a long run, I "level up", and the belt tool is no longer selected, so I have to go back and plan the run all over again.

**Comment by EmeraldBlock** [comment]
It should be a simple fix, just delete [line 124 of src/js/game/hud/parts/building_placer_logic.js](https://github.com/tobspr/shapez.io/blob/master/src/js/game/hud/parts/building_placer_logic.js#L124) (note that the current building will still be deselected if there is a level up screen, since that is considered a "blocking" overlay)

**Comment by tobspr** [comment]
Tracking here: https://trello.com/c/c3JmW429/504-dont-clear-selected-building-on-level-up
